# Generated by Django 4.2 on 2023-04-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('direction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlergyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alergy', models.CharField(max_length=100)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
