# Generated by Django 4.2 on 2023-04-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergypatient',
            name='alergy',
        ),
        migrations.RemoveField(
            model_name='alergypatient',
            name='id_patient',
        ),
        migrations.AddField(
            model_name='alergypatient',
            name='alergies',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='alergypatient',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='alergypatient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
