# Generated by Django 4.2 on 2023-04-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_alergypatient_alergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergypatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
